name: Publish to npm registry

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v7
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Setup act
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash -s -- -b "/usr/bin"
          # Use the micro image to speed up tests: https://nektosact.com/usage/runners.html
          echo "-P ubuntu-latest=node:24-slim" > $HOME/.actrc

      - name: Publish act-test-runner to npm
        run: |
          pnpm install --frozen-lockfile
          pnpm run check:all
          pnpm run test:all
          pnpm run build
          pnpm publish --provenance --access public --no-git-checks
